CREATE TABLE users
(id BIGINT NOT NULL AUTO_INCREMENT,
 username VARCHAR(300) NOT NULL UNIQUE,
 password VARCHAR(300) NOT NULL,
 admin BOOLEAN DEFAULT FALSE,
 lang VARCHAR(4) DEFAULT 'en',
 CONSTRAINT pk_user_id PRIMARY KEY (id));
